-- INSERT INTO AUTHORS (firstName, lastName) VALUES
-- ('Lokesh', 'Gupta'),
-- ('Deja', 'Vu'),
-- ('Caption', 'America');
--
-- INSERT INTO BOOKS (title, year, author_id) VALUES
-- ('Gita', 1000, 1),
-- ('Deja', 1052, 2),
-- ('Caption', 1999, 3);
--
-- INSERT INTO WRITTEN_BY (author_id, book_id) VALUES
-- (1, 1),
-- (2, 2),
-- (3, 3);