-- DROP TABLE IF EXISTS AUTHORS;
-- DROP TABLE IF EXISTS BOOKS;
-- DROP TABLE IF EXISTS WRITTEN_BY;
--
-- CREATE TABLE AUTHORS
-- (
--     author_id  INT AUTO_INCREMENT PRIMARY KEY,
--     first_name VARCHAR(250) NOT NULL,
--     last_name  VARCHAR(250) NOT NULL,
-- );
--
-- CREATE TABLE BOOKS
-- (
--     book_id   INT AUTO_INCREMENT PRIMARY KEY,
--     author_id INT          NULL,
--     title     VARCHAR(250) NOT NULL,
--     year      INT          NOT NULL
--
-- );